<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE equipos_de_baloncesto [
  <!ELEMENT equipos_de_baloncesto (equipo, equipo)>
  <!ELEMENT equipo (nombre, ciudad, entrenador, jugadores)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT ciudad (#PCDATA)>
  <!ELEMENT entrenador (#PCDATA)>
  <!ELEMENT jugadores (jugador, jugador, jugador, jugador)>
  <!ELEMENT jugador (nombre, posicion)>
  <!ATTLIST jugador
  posicion (Base | Escolta | Alero | Pivot) #REQUIRED>
  <!ELEMENT nacionalidad (#PCDATA)>
]>

<equipos_de_baloncesto>
  <equipo>
    <nombre>Equipo A</nombre>
    <ciudad>Madrid</ciudad>
    <entrenador>Carlos López</entrenador>
    <jugadores>
      <jugador posicion="Base">
        <nombre>Juan Pérez</nombre>
        <nacionalidad>Español</nacionalidad>
      </jugador>
      <jugador posicion="Alero">
        <nombre>Marta Ruiz</nombre>
        <nacionalidad>Argentino</nacionalidad>
      </jugador>
    </jugadores>
  </equipo>
  
  <equipo>
    <nombre>Equipo B</nombre>
    <ciudad>Barcelona</ciudad>
    <entrenador>Ana García</entrenador>
    <jugadores>
      <jugador posicion="Escolta">
        <nombre>Pablo Sánchez</nombre>
        <nacionalidad>Mexicano</nacionalidad>
      </jugador>
      <jugador posicion="Pivot">
        <nombre>Laura López</nombre>
        <nacionalidad>Italiano</nacionalidad>
      </jugador>
    </jugadores>
  </equipo>
</equipos_de_baloncesto>
